version: '3.3'

services:
  ulutrip-nginx:
      image: nginx:1.13-alpine
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - ../nginx:/etc/nginx/conf.d
        - ../back_static:/app/back_static
        - ../back_media:/app/back_media
        - ../../ulultrip-frontend/build:/app/front/build
        - ../../ulultrip-bot:/app/bot
      networks:
        - main-network
        - nginx-network
        - ulultrip-frontend_front-network
        
networks:
  nginx-network:
    driver: bridge
  ulultrip-frontend_front-network:
    external: true